### ISSUE TITLE
cookie已上传，但未能运行

### ISSUE THREAD

**Issue by K032** [lanyeeee/little_heart_bot#1]
![Screenshot_20220525_002636](https://user-images.githubusercontent.com/64523426/170085865-55daf12f-6fea-49b2-b04e-264bcd29bf73.jpg)

**Comment by lanyeeee** [comment]
因为获取小心心的功能休眠了，现在只是帮一些老的用户每天发发弹幕，所以新提交的cookie不会被使用。不过看起来你应该只是想用一下发弹幕的功能，所以我在后台手动帮你把cookie用了，现在应该可以发弹幕了。

**Comment by K032** [comment]
谢谢作者！
